### PR TITLE
use to_json to build message for chrome

### LINKED ISSUE #85: Using a non standard character in chrome_print() input returns an unclear error message
Hey, 

First of all, thanks for the amazing chrome_print(). I just LOVE this functionality! 

I'm using `chrome_print()` to print shiny app elements which are bookmarked. 

I noticed this strange error when using `"` in the url inputs (taking the rstudio gallery example below), which is probably to be found with other parameters. 

``` r
pagedown::chrome_print(
  'https://gallery.shinyapps.io/113-bookmarking-url/?_inputs_&n="France"'
)
#> Error in pagedown::chrome_print("https://gallery.shinyapps.io/113-bookmarking-url/?_inputs_&n=\"France\""): Failed to generate output. Reason: Message must be a valid JSON
```

But it's solved if I use `utils::URLencode` on the URL

``` r 
pagedown::chrome_print(
  utils::URLencode('https://gallery.shinyapps.io/113-bookmarking-url/?_inputs_&n="France"')
)
```

<sup>Created on 2019-03-18 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

IMHO, the `Reason: Message must be a valid JSON` is a little bit esoteric. 

It could be avoided with adding a simple `input <- utils::URLencode(input)` here: https://github.com/rstudio/pagedown/blob/master/R/chrome.R#L52

Will be happy to make a PR if you feel like it.

### PR DESCRIPTION
**Pull request by cderv**
This PR is just about using the `to_json` wrapper to build messages for chrome. 

* Using `to_json` instead of `sprintf` will create safe json. This fixes #85 and closes #86 url encoding is not required
* Using `to_json` to create all messages. This is not necessary but I believe this will be easier to maintain, all the more if we need to add some new _switch_ step

---
This change is [Reviewable](https://reviewable.io/reviews/rstudio/pagedown/88)

### CODE REVIEW

File: R/chrome.R [hunk 1]
```diff
@@ -261,44 +261,57 @@ print_page = function(
...
       token$error <- msg$result$errorText,
       {
       # Command #7 received - Test if the html document uses the paged.js polyfill
       # if not, call the binding when fonts are ready
-        if (!isTRUE(msg$result$result$value))
-          ws$send('{"id":8,"method":"Runtime.evaluate","params":{"expression":"pagedownReady.then(() => {pagedownListener(\'\');})"}}')
+        if (!isTRUE(msg$result$result$value)) {
+          ws$send(to_json(list(
+            id = 8, method = "Runtime.evaluate",
+            params = list(expression = "pagedownReady.then(() => {pagedownListener(\'\');})")
```
Comment (yihui) [inline R/chrome.R]: The backslashes before the single quotes are not really necessary since they are inside a pair of double quotes.

```suggestion
            params = list(expression = "pagedownReady.then(() => {pagedownListener('');})")
```
