### PR TITLE
Fix/lua error pandoc

### LINKED ISSUE #245: Fix Lua filer error with recent Pandoc
It seems recent change in Pandoc have created an issue in Lua filters

````
Error running filter C:/Users/chris/Documents/DEV_R/pagedown/inst/resources/lua/loft.lua:
[string "--[[..."]:123: Constructor for MetaInlines failed: [string "--[[..."]:166: attempt to call a nil value (field 'Str')

stack traceback:
	[C]: in function 'error'
	[string "--[[..."]:123: in field 'MetaInlines'
	...ris/Documents/DEV_R/pagedown/inst/resources/lua/loft.lua:21: in function <...ris/Documents/DEV_R/pagedown/inst/resources/lua/loft.lua:17>
````

We need to fix that, and also do #240 so that we can know in advance when something is breaking.

### PR DESCRIPTION
**Pull request by cderv**
Following a change in Pandoc 2.16, some adjustment needs to be made

Fix #245

### CODE REVIEW

**Comment by cderv** [comment]
Test are now passing - so I guess this is good. 

@RLesur I let you check and merge if this is ok for you. 

We could plan a quick release after that so that nobodies encounter this issue. :)

File: inst/resources/lua/loft.lua [hunk 1]
```diff
@@ -13,15 +13,36 @@ local options = {}     -- where we store pandoc Meta
 local tablesList = {}  -- where we store the list of tables
 local figuresList = {} -- where we store the list of figures
 
+-- for debuging purpose
+local debug_mode = os.getenv("DEBUG_PANDOC_LUA") == "TRUE"
+local function print_debug(label,obj,iter)
```
Comment (RLesur) [inline inst/resources/lua/loft.lua:18]: Great helper function!

**Review by RLesur — APPROVED** [review]
LGTM, thanks, @cderv!
